export default {
  'en-us': {
    barText: 'Blog',
    postsTitle: 'All posts',
    list: [
      {
        title: 'Sentinel 1.8.4 released',
        author: 'Eric Zhao',
        dateStr: 'Apr 12nd，2022',
        desc: 'Sentinel 1.8.4 has been released with improvements and bug fixes.',
        link: '/en-us/blog/sentinel-1-8-4-release.html',
      },
      {
        title: 'Sentinel Go v1.0.4 released',
        author: 'Eric Zhao',
        dateStr: 'Jan 10th，2022',
        desc: 'Sentinel Go v1.0.4 has been released with cool features like Prometheus metric exporter and improved circuit breaker half-open recovery strategy.',
        link: '/en-us/blog/sentinel-go-1-0-4-release.html',
      },
      {
        title: 'Sentinel 1.8.3 released',
        author: 'Eric Zhao',
        dateStr: 'Dec 31st，2021',
        desc: 'Sentinel 1.8.3 has been released with cool features including JMX metric exporter support and Envoy RLS v3 API support.',
        link: '/en-us/blog/sentinel-1-8-3-release.html',
      },
      {
        title: 'Sentinel Go v1.0.0 GA released',
        author: 'Eric Zhao',
        dateStr: 'Nov 27th，2020',
        desc: 'Sentinel Go v1.0.0 has been released! Sentinel Go has been production-ready and generally-available.',
        link: '/en-us/blog/sentinel-go-ga-release.html',
      },
      {
        title: 'Sentinel 1.8.0 released',
        author: 'Eric Zhao',
        dateStr: 'Aug 20th，2020',
        desc: 'Sentinel 1.8.0 annual version released with cool features like circuit breaking improvements and Quarkus support.',
        link: '/en-us/blog/sentinel-1-8-0-release.html',
      },
      {
        title: 'Guideline: Migration from Hystrix to Sentinel',
        author: 'Eric Zhao',
        dateStr: 'Nov 29th，2018',
        desc: 'This blog post will introduce how to migrate from Netflix Hystrix to Sentinel',
        link: '/en-us/blog/guideline-migrate-from-hystrix-to-sentinel.html',
      },
      {
        title: 'Sentinel: The flow sentinel of Apache RocketMQ',
        author: 'Eric Zhao',
        dateStr: 'July 27th，2018',
        desc: 'This blog post describes the best practice of using Sentinel in MQ',
        link: '/en-us/blog/sentinel-flow-sentinel-of-rocketmq.html',
      },
    ],
  },
  'zh-cn': {
    barText: '博客',
    postsTitle: '所有文章',
    list: [
      {
        title: '设计稳定的微服务系统时不得不考虑的场景',
        author: '泮圣伟(十眠)',
        desc: '流控降级与容错是我们设计稳定的微服务系统时不得不考虑的场景，如果我们设计每一套系统都要花许多心思来设计系统的流控降级与容错能力，这将会成为让我们每一个开发者都头疼的问题。当我们接触与设计了那么多系统的流控降级后，有没什么通用的场景、最佳实践、设计标准与规范乃至参考实现可以沉淀的？本文详细介绍了流控降级与容错的场景、标准与实践。',
        dateStr: '2022.07.05',
        link: '/zh-cn/blog/necessary-scenarios-of-designing-resilient-microservices.html',
      },
      {
        title: 'Sentinel 1.8.4 版本发布',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.8.4 版本发布，带来多项特性改进与 bug 修复。',
        dateStr: '2022.04.12',
        link: '/zh-cn/blog/sentinel-1-8-4-release.html',
      },
      {
        title: 'Sentinel Go v1.0.4 发布',
        author: 'Eric Zhao',
        desc: 'Sentinel Go v1.0.4 版本发布，带来 Prometheus metric exporter 等多项特性改进与 bug 修复。',
        dateStr: '2022.01.10',
        link: '/zh-cn/blog/sentinel-go-1-0-4-release.html',
      },
      {
        title: 'Sentinel 1.8.3 版本发布',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.8.3 版本发布，带来多项特性改进与 bug 修复。',
        dateStr: '2021.12.31',
        link: '/zh-cn/blog/sentinel-1-8-3-release.html',
      },
      {
        title: 'Sentinel Go v1.0.3 发布',
        author: 'Eric Zhao',
        desc: 'Sentinel Go v1.0.3 版本发布，带来多项特性改进与 bug 修复。',
        dateStr: '2021.08.16',
        link: '/zh-cn/blog/sentinel-go-1-0-3-release.html',
      },
      {
        title: 'Sentinel 1.8.2 版本发布',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.8.2 版本发布，带来多项特性改进与 bug 修复。',
        dateStr: '2021.07.06',
        link: '/zh-cn/blog/sentinel-1-8-2-release.html',
      },
      {
        title: '【编程之夏】中科院开源软件供应链点亮计划 2021 Sentinel 项目招募',
        author: 'Eric Zhao',
        desc: '中科院开源软件供应链点亮计划 2021 Sentinel 项目开始招募啦，欢迎各位在校同学报名~',
        dateStr: '2021.06.01',
        link: '/zh-cn/blog/summer-of-code-2021.html',
      },
      {
        title: 'Sentinel 1.8.1 版本发布',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.8.1 版本发布，带来多项特性改进与 bug 修复。',
        dateStr: '2021.02.04',
        link: '/zh-cn/blog/sentinel-1-8-1-release.html',
      },
      {
        title: 'Sentinel Go 正式 GA，助力云原生服务稳稳稳',
        author: 'Eric Zhao',
        desc: 'Sentinel Go 1.0 GA 版本正式发布，标志着 Go 版本正式进入生产可用阶段。',
        dateStr: '2020.11.28',
        link: '/zh-cn/blog/sentinel-go-ga-release.html',
      },
      {
        title: 'Sentinel Go 0.6.0 发布，支持 Warm-Up 预热流控',
        author: 'Eric Zhao',
        desc: 'Sentinel Go 0.6.0 发布，带来了 Warm-Up 预热流控、go-micro 框架适配等全新特性。',
        dateStr: '2020.09.02',
        link: '/zh-cn/blog/sentinel-golang-0-6-0-release.html',
      },
      {
        title: 'Sentinel 1.8.0 年度版本发布，熔断降级重构升级',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.8.0 年度版本发布，带来了重构升级版的熔断降级及云原生开源生态。',
        dateStr: '2020.08.20',
        link: '/zh-cn/blog/sentinel-1-8-0-release.html',
      },
      {
        title: 'Sentinel Go 0.5.0 发布',
        author: 'Eric Zhao',
        desc: 'Sentinel Go 0.5.0 发布，完善核心功能及性能，同时也带来了 Consul 和 Nacos 数据源扩展支持',
        dateStr: '2020.07.29',
        link: '/zh-cn/blog/sentinel-golang-0-5-0-release.html',
      },
      {
        title: 'Sentinel Go 0.4.0 发布，支持热点流量防护能力',
        author: 'Eric Zhao',
        desc: 'Sentinel Go 0.4.0 版本发布，带来了热点参数流控特性。',
        dateStr: '2020.06.29',
        link: '/zh-cn/blog/sentinel-golang-0-4-0-release.html',
      },
      {
        title: 'Sentinel Go 0.3.0 发布，支持熔断降级能力',
        author: 'Eric Zhao',
        desc: 'Sentinel Go 0.3.0 版本发布，带来了熔断降级规则、etcd 动态数据源等全新特性。',
        dateStr: '2020.05.25',
        link: '/zh-cn/blog/sentinel-golang-0-3-0-release.html',
      },
      {
        title: 'Sentinel 1.7.2 发布，引入 Logger 扩展机制、Zuul 2.x 和 SOFARPC 支持',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.7.2 版本发布，带来了 Logger SPI 扩展机制、Zuul 2.x 网关流控、SOFARPC 适配等多项特性和改进。',
        dateStr: '2020.04.08',
        link: '/zh-cn/blog/sentinel-1-7-2-release.html',
      },
      {
        title: 'Sentinel Go 0.2.0 发布，完善易用性与开源生态',
        author: 'Eric Zhao',
        desc: 'Sentinel Go 0.2.0 版本发布，新增 gRPC、Gin、Dubbo-go 等框架的适配，新增动态文件数据源支持。',
        dateStr: '2020.03.30',
        link: '/zh-cn/blog/sentinel-golang-0-2-0-release.html',
      },
      {
        title: '迈向云原生，Sentinel Golang 首个版本发布',
        author: 'Eric Zhao',
        desc: 'Sentinel 多语言俱乐部迎来新的一员 —— Sentinel Golang 首个原生版本 0.1.0 正式发布！',
        dateStr: '2020.02.13',
        link: '/zh-cn/blog/sentinel-golang-v1-go-go-go.html',
      },
      {
        title: 'Sentinel 1.7.1 发布，多项特性与改进',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.7.1 版本发布，带来了 Spring Web 模块适配、Dubbo 异步模式适配改进、控制台 ACL 注解扩展等多项特性和改进。',
        dateStr: '2019.12.25',
        link: '/zh-cn/blog/sentinel-1-7-1-release.html',
      },
      {
        title: 'Sentinel 1.7.0 发布，支持 Envoy 集群流量控制',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.7.0 版本发布，引入了 Envoy 集群流量控制支持、properties 文件配置、Consul/Etcd/Spring Cloud Config 动态数据源适配等多项新特性与改进。',
        dateStr: '2019.11.12',
        link: '/zh-cn/blog/sentinel-1-7-0-release.html',
      },
      {
        title: 'Sentinel 1.6.3 版本发布，引入网关流控控制台支持',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.6.3 版本发布，引入网关流控控制台支持。',
        dateStr: '2019.07.29',
        link: '/zh-cn/blog/sentinel-1-6-3-release.html',
      },
      {
        title: 'Sentinel 1.6.0 正式发布，引入网关流控场景支持',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.6.0 版本正式发布，引入网关流控场景支持以及注解 fallback 改进。',
        dateStr: '2019.04.24',
        link: '/zh-cn/blog/sentinel-1-6-0-release.html',
      },
      {
        title: 'Sentinel 1.5.1 正式发布',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.5.1 版本正式发布，主要包含一些 bug 修复和功能改进，同时添加了兼容 Dubbo 2.7.x 的适配模块。',
        dateStr: '2019.03.28',
        link: '/zh-cn/blog/sentinel-1-5-1-release.html',
      },
      {
        title: 'Sentinel 1.5.0 正式发布，引入 Reactive 支持',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.5.0 版本正式发布，引入 Reactive 支持、滑动窗口占用机制等多项新特性。',
        dateStr: '2019.03.14',
        link: '/zh-cn/blog/sentinel-1-5-0-release.html',
      },
      {
        title: 'Sentinel 1.4.2 正式发布',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.4.2 版本发布，引入 Zuul 1.x 适配，完善了集群流控相关的功能。',
        dateStr: '2019.02.21',
        link: '/zh-cn/blog/sentinel-1-4-2-release.html',
      },
      {
        title: 'Sentinel 1.4.1 正式发布',
        author: 'Eric Zhao',
        desc: 'Sentinel 1.4.1 版本发布，完善 Sentinel 控制台的集群流控管理功能。',
        dateStr: '2019.01.04',
        link: '/zh-cn/blog/sentinel-1-4-1-release.html',
      },
      {
        title: 'Guideline: 从 Hystrix 迁移到 Sentinel',
        author: 'Eric Zhao',
        dateStr: '2018.11.29',
        desc: '本文将帮助您从 Hystrix 迁移到 Sentinel，并帮助您快速了解 Sentinel 的使用。',
        link: '/zh-cn/blog/guideline-migrate-from-hystrix-to-sentinel.html',
      },
      {
        title: 'Sentinel 1.3.0 重磅发布',
        author: 'Eric Zhao',
        dateStr: '2018.10.31',
        desc: 'Sentinel 1.3.0 GA 版本正式发布，提供功能完善的控制台。',
        link: '/zh-cn/blog/sentinel-1-3-0-release.html',
      },
      {
        title: 'Sentinel 0.2.0 重磅发布',
        author: 'Eric Zhao',
        dateStr: '2018.09.27',
        desc: '介绍 Sentinel 0.2.0 的核心功能，包括异步调用支持、热点参数限流等。',
        link: '/zh-cn/blog/sentinel-0-2-0-release.html',
      },
      {
        title: 'Sentinel 与 Hystrix 的对比',
        author: 'Eric Zhao',
        dateStr: '2018.08.10',
        desc: '对 Sentinel 与 Hystrix 的设计思想和主要特性进行对比。',
        link: '/zh-cn/blog/sentinel-vs-hystrix.html',
      },
      {
        title: 'Sentinel 为 Apache RocketMQ 保驾护航',
        author: 'Eric Zhao',
        dateStr: '2018.07.27',
        desc: '主要介绍了 Sentinel 在消息队列 Apache RocketMQ 削峰填谷场景下的最佳实践。',
        link: '/zh-cn/blog/sentinel-flow-sentinel-of-rocketmq.html',
      },
      {
        title: 'Sentinel 为 Dubbo 保驾护航',
        author: 'Eric Zhao',
        dateStr: '2018.07.24',
        desc: '主要介绍了在 Dubbo 中整合使用 Sentinel 的最佳实践。',
        link: '/zh-cn/blog/sentinel-flow-sentinel-of-dubbo.html',
      },
    ],
  },
};
